### ISSUE TITLE
Add breadcrumbs to page header

### ISSUE THREAD

**Issue by stewnight** [stewnight/legacy-grow-app#14]
Add breadcrumbs to the pages header to allow for easier back navigation.
Use just a back button for going to dashboard / home.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add a Breadcrumb component to the layout file and implement breadcrumbs in individual page files. Include a back button for navigating to the dashboard/home.

You can review changes in this commit: https://github.com/lkilu6456546/stewnight-legacy-grow-app-14/commit/738ad5b0d2be20fed031375e589bcaf2869116ba.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
